== \(\TeX\) equations with equation references
:stem: latexmath
:eqnums: AMS

演示 Asciidoctor 公式引用, 与 https://mathjax.github.io/MathJax-demos-web/equation-refs.html[Mathjax Equation References 示例]有区别, 见 https://github.com/asciidoctor/asciidoctor/issues/3518[Add support for equation numbering and cross-referencing #3518]

[NOTE]
====
在 Asciidoctor 中, `\[...\]` 形式的公式不会自动编号, 必须使用 `\begin{} ... \end{}` 形式.
====

Here is a labeled equation:

\begin{equation}
x+1\over\sqrt{1-x^2}\label{ref1}
\end{equation}

with a reference to ref1: \ref{ref1},
and another numbered one with no label:

\begin{equation} 
x+1\over\sqrt{1-x^2} 
\end{equation}

This one uses \nonumber:

\begin{equation}  
x+1\over\sqrt{1-x^2}\nonumber 
\end{equation}

Here's one using the equation environment:

\begin{equation}
x+1\over\sqrt{1-x^2}
\end{equation}

and one with equation* environment:

\begin{equation*}
x+1\over\sqrt{1-x^2}
\end{equation*}

This is a forward reference [\ref{ref2}] and another \eqref{ref2} for the following equation:

\begin{equation}
x+1\over\sqrt{1-x^2}\label{ref2}
\end{equation}

More math:

\begin{equation} 
x+1\over\sqrt{1-x^2} 
\end{equation}

Here is a ref inside math: \(\ref{ref2}+1\) and text after it.

\begin{align} 
x& = y_1-y_2+y_3-y_5+y_8-\dots 
&& \text{by \eqref{ref1}}\\ 
& = y'\circ y^* && \text{(by \eqref{ref3})}\\ 
& = y(0) y' && \text {by Axiom 1.} 
\end{align} 

Here's a bad ref [\ref{ref4}] to a nonexistent label.

An alignment:

\begin{align}
a&=b\label{ref3}\cr
&=c+d
\end{align}

and a starred one:

\begin{align*}
a&=b\cr
&=c+d
\end{align*}
