== Sample MathJax Equations
:stem:

演示 Asciidoctor 公式渲染, 与 https://mathjax.github.io/MathJax-demos-web/tex-chtml.html[Sample MathJax Equations 示例]有区别(如: 重新定义分隔符)

When \$a \ne 0\$, there are two solutions to \(ax^2 + bx + c = 0\) and they are
\[x = {-b \pm \sqrt{b^2-4ac} \over 2a}.\]

The Lorenz Equations

\begin{align}
\dot{x} &= \sigma(y-x) \\
\dot{y} &= \rho x - y - xz \\
\dot{z} &= -\beta z + xy
\end{align}

The Cauchy-Schwarz Inequality

\[
\left( \sum_{k=1}^n a_k b_k \right)^2 
\leq
\left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)
\]

A Cross Product Formula

\[
\mathbf{V}_1 \times \mathbf{V}_2 = 
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial X}{\partial u} & \frac{\partial Y}  {\partial u} & 0 \\
\frac{\partial X}{\partial v} & \frac{\partial Y}  {\partial v} & 0 \\
\end{vmatrix}
\]

The probability of getting \(k\) heads when flipping \(n\) coins is:

\[ P(E) = {n \choose k} p^k (1-p)^{ n-k} \]

An Identity of Ramanujan

\[
\frac{1}{(\sqrt{\phi \sqrt{5}}-\phi) e^{\frac25 \pi}} =
 1+\cfrac{e^{-2\pi}} {1+\cfrac{e^{-4\pi}} {1+\cfrac{e^{-6\pi}}
  {1+\cfrac{e^{-8\pi}} {1+\ldots} } } }
\]

A Rogers-Ramanujan Identity

+\[
1 + \frac{q^2}{(1-q)} + \frac{q^6}{(1-q)(1-q^2)} + \cdots =
\prod_{j=0}^{\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})}, \text{ for } |q| < 1.
\]+

[NOTE]
====
Asciidoctor 处理上面的公式时将 `^` 转换成了`<sup>...</sup>` 标签, 导致 Mathjax 解析错误, 解决方法见: https://github.com/asciidoctor/asciidoctor/issues/1058[Incorrect transformation of math #1058]

对于多行公式, 下面的格式最可靠:
```
  [stem]
  ++++
  ...
  ++++
```
====

Maxwell's Equations

\begin{align}
  \nabla \times \vec{\mathbf{B}} -\, \frac1c\, \frac{\partial\vec{\mathbf{E}}}{\partial t} &= \frac{4\pi}{c}\vec{\mathbf{j}} \\
  \nabla \cdot \vec{\mathbf{E}} &= 4 \pi \rho \\
  \nabla \times \vec{\mathbf{E}}\, +\, \frac1c\, \frac{\partial\vec{\mathbf{B}}}{\partial t} &= \vec{\mathbf{0}} \\
  \nabla \cdot \vec{\mathbf{B}} &= 0
\end{align}

In-line Mathematics

Finally, while display equations look good for a page of samples, the ability to mix math and text in a paragraph is also important.  This expression \$\sqrt{3x-1}+(1+x)^2\$ is an example of an inline equation.  As you see, MathJax equations can be used this way as well, without unduly disturbing the spacing between lines
